Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -5,7 +5,7 @@ substitutions:
   _COMPOSER_REGION: asia-south1
   _COMPOSER_ENV_NAME: airflow-cicd1
   _ROLLBACK: 'false'
-#   _SEVERITY: MEDIUM
+  _SEVERITY: MEDIUM
   _SEVERITY1: HIGH
   _SEVERITY2: CRITICAL
   
@@ -102,18 +102,18 @@ steps:
           then echo 'Failed vulnerability check - HIGH'
           exit 1 
           fi
-#   - id: severity check
-#     name: gcr.io/cloud-builders/gcloud
-#     entrypoint: /bin/bash
-#     args:
-#      - -c
-#      - | 
-#        gcloud artifacts docker images list-vulnerabilities \
-#         $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
-#         | if grep -Fxq $_SEVERITY 
-#           then echo 'Failed vulnerability check - MEDIUM'
-#           exit 1 
-#           fi
+  - id: severity check
+    name: gcr.io/cloud-builders/gcloud
+    entrypoint: /bin/bash
+    args:
+     - -c
+     - | 
+       gcloud artifacts docker images list-vulnerabilities \
+        $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
+        | if grep -Fxq $_SEVERITY 
+          then echo 'Failed vulnerability check - MEDIUM'
+          exit 1 
+          fi
     
 # Push the image to GCR
   - name: 'gcr.io/cloud-builders/docker'
