Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -5,9 +5,9 @@ substitutions:
   _COMPOSER_REGION: asia-south1
   _COMPOSER_ENV_NAME: airflow-cicd1
   _ROLLBACK: 'false'
-  _SEVERITY: MEDIUM
-  _SEVERITY1: HIGH
-  _SEVERITY2: CRITICAL
+#   _SEVERITY: MEDIUM
+#   _SEVERITY1: HIGH
+#   _SEVERITY2: CRITICAL
   
 # Access the id_github file from Secret Manager, and setup SSH
 steps:
@@ -58,15 +58,15 @@ steps:
   - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
     args:
     - '-Dsonar.host.url=http://35.244.55.55:9000/ '
-    - '-Dsonar.login=sqp_78d4c4d00e71fc99a703f80d38fee3b6618ee95a'
-    - '-Dsonar.projectKey=sonar-test-1 '
+    - '-Dsonar.login=sqp_3da0ffa7dac3db78b281bc29b1419cb2b1b19ba6'
+    - '-Dsonar.projectKey=UAT-airflow-cicd'
     - '-Dsonar.sources=.'
     - '-Dsonar.python.coverage.reportPaths=coverage.xml'
 
   
 # Build the image
   - name: 'gcr.io/cloud-builders/docker'
-    args: ['build', '-t', 'gcr.io/niveustraining/airflow-image:v2.0', '.']
+    args: ['build', '-t', 'gcr.io/niveustraining/airflow-image-uat:v2.0', '.']
 
   - id: scan
     name: gcr.io/cloud-builders/gcloud
@@ -74,7 +74,7 @@ steps:
     args:
      - -c
      - |
-       gcloud artifacts docker images scan 'gcr.io/niveustraining/airflow-image:v2.0' \
+       gcloud artifacts docker images scan 'gcr.io/niveustraining/airflow-image-uat:v2.0' \
        --format='value(response.scan)' > /workspace/docdags/scan_id.txt
        
   - id: severity check2
@@ -90,39 +90,39 @@ steps:
           exit 1 
           fi
           
-  - id: severity check1
-    name: gcr.io/cloud-builders/gcloud
-    entrypoint: /bin/bash
-    args:
-     - -c
-     - | 
-       gcloud artifacts docker images list-vulnerabilities \
-        $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
-        | if grep -Fxq $_SEVERITY1
-          then echo 'Failed vulnerability check - HIGH'
-          exit 1 
-          fi
-  - id: severity check
-    name: gcr.io/cloud-builders/gcloud
-    entrypoint: /bin/bash
-    args:
-     - -c
-     - | 
-       gcloud artifacts docker images list-vulnerabilities \
-        $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
-        | if grep -Fxq $_SEVERITY 
-          then echo 'Failed vulnerability check - MEDIUM'
-          exit 1 
-          fi
+#   - id: severity check1
+#     name: gcr.io/cloud-builders/gcloud
+#     entrypoint: /bin/bash
+#     args:
+#      - -c
+#      - | 
+#        gcloud artifacts docker images list-vulnerabilities \
+#         $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
+#         | if grep -Fxq $_SEVERITY1
+#           then echo 'Failed vulnerability check - HIGH'
+#           exit 1 
+#           fi
+#   - id: severity check
+#     name: gcr.io/cloud-builders/gcloud
+#     entrypoint: /bin/bash
+#     args:
+#      - -c
+#      - | 
+#        gcloud artifacts docker images list-vulnerabilities \
+#         $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
+#         | if grep -Fxq $_SEVERITY 
+#           then echo 'Failed vulnerability check - MEDIUM'
+#           exit 1 
+#           fi
     
 # Push the image to GCR
   - name: 'gcr.io/cloud-builders/docker'
-    args: ['push', 'gcr.io/niveustraining/airflow-image:v2.0']
+    args: ['push', 'gcr.io/niveustraining/airflow-image-uat:v2.0']
 
 # vulnerability scan
 
   - name: 'gcr.io/cloud-builders/gcloud'
-    args: ['beta', 'container', 'images', 'describe', 'gcr.io/niveustraining/airflow-image:v2.0', '--format=json']
+    args: ['beta', 'container', 'images', 'describe', 'gcr.io/niveustraining/airflow-image-uat:v2.0', '--format=json']
 
 # Removing the old build Dags object
   - name: 'gcr.io/cloud-builders/gsutil'
@@ -133,7 +133,7 @@ steps:
         gsutil -m rm -r gs://asia-south1-airflow-cicd1-99651280-bucket/dags/*
   
 # Pull the Older Image and get the previous dags
-  - name: gcr.io/niveustraining/airflow-image:v2.0
+  - name: gcr.io/niveustraining/airflow-image-uat:v2.0
     entrypoint: /bin/bash
     args:
     - -c
